name: Polybot Service Build

# Trigger workflow only when pushed to branch main, directory polybot
on:
  push:
    branches:
      - main
    paths:
      - 'polybot/**'

jobs:
  PolybotBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          cd polybot
          
          # Login to DockerHub        
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/polybot:v2.0.${{ github.run_number }}-polybot-k8s
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  UpdatePolybotInfra:
    runs-on: ubuntu-latest
    needs:
      - PolybotBuild

    steps:
      - name: Trigger PolybotInfra Dispatch Workflow
        run: |
          # Curl to PolybotInfra repo and activate the workflow dispatch
          echo "Triggering PolybotInfra Dispatch Workflow with the following params : {service_name:polybot,image:$IMAGE_NAME}"
          
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.POLYBOTINFRA_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/barrotem/PolybotInfra/actions/workflows/service-deploy.yaml/dispatches \
          -d '{"ref":"main","inputs":{"service_name":"polybot","image":\"${{ secrets.DOCKERHUB_USERNAME }}/polybot\:v2.0.${{ github.run_number }}-polybot-k8s\"}}'
