name: Polybot Service Build

# Trigger workflow only when pushed to branch main, directory polybot
on:
  push:
    branches:
      - main
    paths:
      - 'yolo5/**'

# Define IMAGE_NAME as an environment variable to be used throughout the workflow
env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/yolo5:v2.0.${{ github.run_number }}-polybot-k8s

jobs:
  Yolo5Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          cd yolo5
          
          # Login to DockerHub        
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  UpdatePolybotInfra:
    runs-on: ubuntu-latest
    needs:
      - Yolo5Build

    steps:
      - name: Trigger PolybotInfra Dispatch Workflow
        run: |
          # Curl to PolybotInfra repo and activate the workflow dispatch
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.POLYBOTINFRA_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/barrotem/PolybotInfra/actions/workflows/service-deploy.yaml/dispatches \
          -d '{"ref":"main","inputs":{"service_name":"yolo5","image":"$IMAGE_NAME"}}'
